### PR TITLE
policy download refactor

### LINKED ISSUE #614: failed to initialize terrascan. error : failed to install policies
* terrascan version: v1.4.0
* Operating System: Ubuntu 18.04 LTS

### Description

Running `terrascan init` or `terrascan scan` yields the following output:

```
2021-03-14T11:00:42.987+0100    error   cli/init.go:42  failed to initialize terrascan. error : failed to install policies to '/home/christophetd/.terrascan'. error: 'rename /tmp/terrascan-522112316 /home/christophetd/.terrascan: invalid cross-device link'
```

### What I Did

- Creating `/home/christophetd/.terrascan` manually did not fix the issue. It actually seems `terrascan init` removes it.
- Manually cloning https://github.com/accurics/terrascan.git to ~/.terrascan seems to fix the issue

### PR DESCRIPTION
**Pull request by dev-gaur**
fixes #614

### CODE REVIEW

File: pkg/initialize/run.go [hunk 1]
```diff
@@ -99,15 +106,10 @@ func DownloadPolicies() error {
...
-	if err = os.Rename(tempPath, basePath); err != nil {
-		return fmt.Errorf("failed to install policies to '%s'. error: '%v'", basePath, err)
-	}
-
 	return nil
 }
+
+func connected(url string) bool {
+	_, err := http.Get(url)
+	return err == nil
```
Comment (jlk) [inline pkg/initialize/run.go:114]: Thinking about the use case for when it can't get `url` - do we want to print the error detail? User isn't sure if it's can't connect, can't lookup dns name, or something else...

**Review by jlk — APPROVED** [review]
Generally looks good. Could maybe improve logging in connected()?

File: pkg/initialize/run.go (hunk 1 above)
Comment (dev-gaur) [reply pkg/initialize/run.go:114]: we can tackle that in #576
