### PR TITLE
Fixes incorrect filepath reporting in sarif output & added e2e tests for sarif output

### LINKED ISSUE #861: Sarif output has wrong file path value for file scans
### Directory Scan
```
./bin/terrascan scan -d pkg/iac-providers/terraform/v14/testdata/relative-moduleconfigs/elasticcache/ -o sarif                                                                                                                                        
{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "terrascan",
          "version": "1.7.0",
          "informationUri": "https://github.com/accurics/terrascan",
          "rules": [
            {
              "id": "AWS.ElastiCache.DataSecurity.High.0424",
              "name": "noMemcachedInElastiCache",
              "shortDescription": {
                "text": "ElastiCache for Memcached is not in use in AWS PCI DSS environments"
              },
              "properties": {
                "category": "Compliance Validation",
                "severity": "HIGH"
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "AWS.ElastiCache.DataSecurity.High.0424",
          "level": "error",
          "message": {
            "text": "ElastiCache for Memcached is not in use in AWS PCI DSS environments"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///Users/dev-gaur/go/src/github.com/accurics/terrascan/pkg/iac-providers/terraform/v14/testdata/relative-moduleconfigs/elasticcache/main.tf"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "name": "noMemcachedInElastiCache",
                  "kind": "aws_elasticache_cluster"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

Check the artifactLocation.url value. It works fine for Directory scans, but works a bit wrong for File scans. Check the example below.

### File Scan
```
./bin/terrascan scan -f pkg/iac-providers/terraform/v14/testdata/relative-moduleconfigs/elasticcache/main.tf -o sarif                                                                                                                                 
{
  "version": "2.1.0",
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "runs": [
    {
      "tool": {
        "driver": {
          "name": "terrascan",
          "version": "1.7.0",
          "informationUri": "https://github.com/accurics/terrascan",
          "rules": [
            {
              "id": "AWS.ElastiCache.DataSecurity.High.0424",
              "name": "noMemcachedInElastiCache",
              "shortDescription": {
                "text": "ElastiCache for Memcached is not in use in AWS PCI DSS environments"
              },
              "properties": {
                "category": "Compliance Validation",
                "severity": "HIGH"
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "AWS.ElastiCache.DataSecurity.High.0424",
          "level": "error",
          "message": {
            "text": "ElastiCache for Memcached is not in use in AWS PCI DSS environments"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file:///Users/dev-gaur/go/src/github.com/accurics/terrascan/pkg/iac-providers/terraform/v14/testdata/relative-moduleconfigs/elasticcache/main.tf/main.tf"
                },
                "region": {
                  "startLine": 1
                }
              },
              "logicalLocations": [
                {
                  "name": "noMemcachedInElastiCache",
                  "kind": "aws_elasticache_cluster"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by dev-gaur**
fixes #861

### CODE REVIEW

**Review by kanchwala-yusuf — APPROVED** [review]
Please run `go mod tidy` on this PR as well

File: pkg/utils/file.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+// GetFileMode fetches the filemode from a file path
+func GetFileMode(path string) os.FileMode {
+	fi, err := os.Stat(path)
+	if err != nil {
+		if os.IsNotExist(err) {
+			zap.S().Errorf("file %s does not exist.", path)
+		} else {
+			zap.S().Errorf("unable to fetch file info for path %s.", path)
+		}
```
Comment (Rchanger) [inline pkg/utils/file.go:16]: This method may panic. os.Stat() returns nil file info on an error and we are just logging the error and not returning.

**Review by Rchanger — CHANGES_REQUESTED** [review]

File: pkg/utils/file.go [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package utils
```
Comment (patilpankaj212) [inline pkg/utils/file.go:1]: missing copyright header?

File: pkg/utils/json.go [hunk 3]
```diff
@@ -73,3 +73,23 @@ func AreEqualJSON(s1, s2 string) (bool, error) {
 
 	return reflect.DeepEqual(o1, o2), nil
 }
+
+// AreEqualJSONBytes validate if two json byte arrays are equal
+func AreEqualJSONBytes(b1, b2 []byte) (bool, error) {
```
Comment (patilpankaj212) [inline pkg/utils/json.go:78]: Is it possible to use `AreEqualJSON` already present in the file?
If not, I think we can refactor `AreEqualJSON` func.

File: pkg/writer/sarif.go [hunk 4]
```diff
@@ -99,3 +97,13 @@ func getSarifLevel(severity string) string {
 
 	return m[strings.ToLower(severity)]
 }
+
+func getAbsoluteFilePath(resourcePath, filePath string) string {
+	if !filepath.IsAbs(resourcePath) {
+		resourcePath, _ = filepath.Abs(resourcePath)
```
Comment (patilpankaj212) [inline pkg/writer/sarif.go:103]: Even though error seems unlikely here, I think we should handle error case too !!

File: test/e2e/scan/scan_utils.go [hunk 5]
```diff
@@ -84,3 +94,123 @@ func RunScanCommand(terrascanBinaryPath, relGoldenFilePath string, exitCode int,
...
 	return session, goldenFileAbsPath
 }
+
+// GetSarifGoldenString gives out golden sarif format string
+func GetSarifGoldenString(template, terrascanVersion string, absfilepath string) string {
+	return fmt.Sprintf(template, terrascanVersion, fmt.Sprintf("file://%s", absfilepath))
+}
+
+// SarifTemplateAWSAMIViolation string
+const SarifTemplateAWSAMIViolation = `{
```
Comment (patilpankaj212) [inline test/e2e/scan/scan_utils.go:104]: I was wondering if we can use golden text files instead of a template. Is it possible?

File: test/helper/helper.go [hunk 6]
```diff
@@ -352,3 +371,14 @@ func removeFileAndRoothFromViolations(v violations) {
 		violation.PlanRoot = ""
 	}
 }
+
+// GetAbsoluteFilePathForSarif helper for sarif path
+func GetAbsoluteFilePathForSarif(resourcePath, filePath string) string {
+	if !filepath.IsAbs(resourcePath) {
+		resourcePath, _ = filepath.Abs(resourcePath)
```
Comment (patilpankaj212) [inline test/helper/helper.go:378]: we should handle the error case here too.

**Review by patilpankaj212 — CHANGES_REQUESTED** [review]

File: test/e2e/scan/scan_utils.go (hunk 5 above)
Comment (dev-gaur) [reply test/e2e/scan/scan_utils.go:104]: I think It'll unnecessary add another step of file processing. Maybe we can take this point up in some other refactor phase as such templates are being used in other places as well.

**Review by patilpankaj212 — APPROVED** [review]

**Review by Rchanger — APPROVED** [review]
