### PR TITLE
fix - terraform complex variables are not getting resolved

### LINKED ISSUE #656: terrascan doesn't resolve terraform complex variables
* terrascan version: 1.4.0
* Operating System: all

### Description

when terraform config has reference to complex variables like list(object), map(object), list(tuple), tuple with object etc, its value is not resolved.

### What I Did

created a terraform config which used complex variables of type specified above.

### PR DESCRIPTION
**Pull request by patilpankaj212**
1. fixes #656 
2. unit tests

### CODE REVIEW

File: pkg/iac-providers/terraform/commons/cty-converters_test.go [hunk 1]
```diff
@@ -503,3 +503,206 @@ func TestCtyToMap(t *testing.T) {
...
+				ctyVal: unsignedIntCtyVal,
+			},
+			want: 44,
+		},
+		{
+			name: "string input",
+			args: args{
+				ctyVal: stringCtyVal,
+			},
+			want: "Peter Parker",
```
Comment (kanchwala-yusuf) [inline pkg/iac-providers/terraform/commons/cty-converters_test.go:550]: I like the reference here :)

**Review by kanchwala-yusuf — APPROVED** [review]
LGTM
