### PR TITLE
shifted opa engine warning message to debug log level

### LINKED ISSUE #709: Failed to run prepared query error in opa/engine.go
* terrascan version: 1.5.0
* Operating System: macOS 11.2.3

### Description

I was trying to test it on my Terraform code but an error keeps occur every moment when I execute it. I think it should be going without any errors, but every code I test it with makes the same error.

`2021-04-29T16:53:45.436+0900	warn	opa/engine.go:346	failed to run prepared query{error 26 0  hardCodedShellScript:22: eval_builtin_error: base64.decode: illegal base64 data at input byte 0} {rule 15 0 'AWS.LaunchConfiguration.DataSecurity.High.0101' <nil>} {file 15 0 hardCodedShellScript.rego <nil>}`

### What I Did

Example Terraform:

```terraform
provider "aws" {
  region = "eu-west-1"
}

locals {
  user_data = <<EOF
#!/bin/bash
echo "Hello Terraform!"
EOF
}
data "aws_vpc" "default" {
  default = true
}

data "aws_subnet_ids" "all" {
  vpc_id = data.aws_vpc.default.id
}

data "aws_ami" "amazon_linux" {
  most_recent = true

  owners = ["amazon"]

  filter {
    name = "name"

    values = [
      "amzn-ami-hvm-*-x86_64-gp2",
    ]
  }

  filter {
    name = "owner-alias"

    values = [
      "amazon",
    ]
  }
}

module "security_group" {
  source  = "terraform-aws-modules/security-group/aws"
  version = "~> 3.0"

  name        = "example"
  description = "Security group for example usage with EC2 instance"
  vpc_id      = data.aws_vpc.default.id

  ingress_cidr_blocks = ["0.0.0.0/0"]
  ingress_rules       = ["http-80-tcp", "all-icmp"]
  egress_rules        = ["all-all"]
}

resource "aws_eip" "this" {
  vpc      = true
  instance = module.ec2.id[0]
}

resource "aws_placement_group" "web" {
  name     = "hunky-dory-pg"
  strategy = "cluster"
}

resource "aws_kms_key" "this" {
}

module "ec2" {
  source = "../../"

  instance_count = 1

  name          = "example-normal"
  ami           = data.aws_ami.amazon_linux.id
  instance_type = "c5.large"
  subnet_id     = tolist(data.aws_subnet_ids.all.ids)[0]
  vpc_security_group_ids      = [module.security_group.this_security_group_id]
  associate_public_ip_address = true
  placement_group             = aws_placement_group.web.id

  user_data_base64 = base64encode(local.user_data)

  root_block_device = [
    {
      volume_type = "gp2"
      volume_size = 10
    },
  ]

  ebs_block_device = [
    {
      device_name = "/dev/sdf"
      volume_type = "gp2"
      volume_size = 5
      encrypted   = true
      kms_key_id  = aws_kms_key.this.arn
    }
  ]

  tags = {
    "Env"      = "Private"
    "Location" = "Secret"
  }
}
```
Below is the actual command and the error message. I tried installing with `brew`, manual build and Docker but it all made the same error. 
```bash
$ terrascan scan
2021-04-29T16:53:45.436+0900	warn	opa/engine.go:346	failed to run prepared query{error 26 0  hardCodedShellScript:22: eval_builtin_error: base64.decode: illegal base64 data at input byte 0} {rule 15 0 'AWS.LaunchConfiguration.DataSecurity.High.0101' <nil>} {file 15 0 hardCodedShellScript.rego <nil>}


Violation Details -

	Description    :	EC2 instances should disable IMDS or require IMDSv2 as this can be related to the weaponization phase of kill chain
	File           :	../../../../../var/folders/m_/9v32lyj95dd5pgy44xgmj7j80000gn/T/cyz88y/main.tf
	Line           :	5
	Severity       :	MEDIUM
	-----------------------------------------------------------------------


Scan Summary -

	File/Folder         :	/Users/user/terraform/production/ubuntu-1804
	IaC Type            :	terraform
	Scanned At          :	2021-04-29 07:53:45.565984 +0000 UTC
	Policies Validated  :	562
	Violated Policies   :	1
	Low                 :	0
	Medium              :	1
	High                :	0
```

### PR DESCRIPTION
**Pull request by dev-gaur**
fixes #709

### CODE REVIEW

File: pkg/policy/opa/engine.go [hunk 1]
```diff
@@ -345,7 +345,7 @@ func (e *Engine) Evaluate(engineInput policy.EngineInput) (policy.EngineOutput,
 		// Execute the prepared query.
 		rs, err := e.regoDataMap[k].PreparedQuery.Eval(e.context, rego.EvalInput(engineInput.InputData))
 		if err != nil {
-			zap.S().Warn("failed to run prepared query", zap.Error(err), zap.String("rule", "'"+k+"'"), zap.String("file", e.regoDataMap[k].Metadata.File))
+			zap.S().Debug("failed to run prepared query", zap.Error(err), zap.String("rule", "'"+k+"'"), zap.String("file", e.regoDataMap[k].Metadata.File))
```
Comment (patilpankaj212) [inline pkg/policy/opa/engine.go:348]: should we decrement the ruleCount when Eval fails?

**Review by patilpankaj212 — APPROVED** [review]

**Review by kanchwala-yusuf — APPROVED** [review]
