### PR TITLE
fix panic for floating point variables

### LINKED ISSUE #652: panic while resolving floating point variable
* terrascan version: 1.4.0
* Operating System: all

### Description

when terraform config file has reference to a floating point variable, terrascan panics while resolving its value.

### What I Did

created a terraform config which uses floating point variable, and ran `terrascan scan`

### PR DESCRIPTION
**Pull request by patilpankaj212**
fixes #652

### CODE REVIEW

File: pkg/iac-providers/terraform/commons/cty-converters.go [hunk 1]
```diff
@@ -58,7 +64,7 @@ func ctyToSlice(ctyVal cty.Value) (interface{}, error) {
 	var val []interface{}
 	var allErrs error
 
-	if strings.Contains(ctyVal.Type().FriendlyName(), "list") {
+	if ctyVal.Type().IsListType() {
```
Comment (kanchwala-yusuf) [inline pkg/iac-providers/terraform/commons/cty-converters.go:67]: Just curious, does `IsListType()` give a more reliable and consistent output?

**Review by kanchwala-yusuf — APPROVED** [review]

**Comment by kanchwala-yusuf** [comment]
@patilpankaj212 , was wondering if we could add a sample terraform config in our unit tests for testing this particular case?
